//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MilNet.Core.Resources {
    using System;
    
    
    /// <summary>
    ///   Une classe de ressource fortement typée destinée, entre autres, à la consultation des chaînes localisées.
    /// </summary>
    // Cette classe a été générée automatiquement par la classe StronglyTypedResourceBuilder
    // à l'aide d'un outil, tel que ResGen ou Visual Studio.
    // Pour ajouter ou supprimer un membre, modifiez votre fichier .ResX, puis réexécutez ResGen
    // avec l'option /str ou régénérez votre projet VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Retourne l'instance ResourceManager mise en cache utilisée par cette classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MilNet.Core.Resources.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Remplace la propriété CurrentUICulture du thread actuel pour toutes
        ///   les recherches de ressources à l'aide de cette classe de ressource fortement typée.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Bug correction.
        /// </summary>
        internal static string BugCorrection {
            get {
                return ResourceManager.GetString("BugCorrection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Deleted feature.
        /// </summary>
        internal static string DeletedFeature {
            get {
                return ResourceManager.GetString("DeletedFeature", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à File {0} can&apos;t be opened..
        /// </summary>
        internal static string FileCantBeOpened {
            get {
                return ResourceManager.GetString("FileCantBeOpened", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à File log created into {0}..
        /// </summary>
        internal static string FileLogCreatedInto {
            get {
                return ResourceManager.GetString("FileLogCreatedInto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à File {0} not found..
        /// </summary>
        internal static string FileNotFound {
            get {
                return ResourceManager.GetString("FileNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à File {0} doesn&apos;t exist. Settings can&apos;t be loaded..
        /// </summary>
        internal static string FileNotFoundSettingsCantBeLoaded {
            get {
                return ResourceManager.GetString("FileNotFoundSettingsCantBeLoaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Folder {0} doesn&apos;t exist. Settings can&apos;t be saved..
        /// </summary>
        internal static string FolderNotFoundSettingsCantBeSaved {
            get {
                return ResourceManager.GetString("FolderNotFoundSettingsCantBeSaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Index not found.
        /// </summary>
        internal static string IndexNotFound {
            get {
                return ResourceManager.GetString("IndexNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Log file {0} can&apos;t be opened..
        /// </summary>
        internal static string LogFileCantBeOpened {
            get {
                return ResourceManager.GetString("LogFileCantBeOpened", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à New feature.
        /// </summary>
        internal static string NewFeature {
            get {
                return ResourceManager.GetString("NewFeature", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à No log file found into {0}..
        /// </summary>
        internal static string NoLogFileFound {
            get {
                return ResourceManager.GetString("NoLogFileFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Operation change.
        /// </summary>
        internal static string OperationChange {
            get {
                return ResourceManager.GetString("OperationChange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Runs can&apos;t be processed into the file {0}..
        /// </summary>
        internal static string RunsCantBeProcessedIntoFile {
            get {
                return ResourceManager.GetString("RunsCantBeProcessedIntoFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à The serie of runs can&apos;t be found into the file {0}..
        /// </summary>
        internal static string SerieOfRunsNotFoundIntoFile {
            get {
                return ResourceManager.GetString("SerieOfRunsNotFoundIntoFile", resourceCulture);
            }
        }
    }
}
